### ISSUE TITLE
Make buttons vertical

### ISSUE THREAD

**Issue by vaarsha** [vaarsha/Bijaka#1]
The active, all and complete buttons needs to be vertically aligned.

**Comment by ghosh** [comment]
Hey, I can help with this. I'll submit a PR soon.

**Comment by markRichie** [comment]
what do you mean by vertical

**Comment by vaarsha** [comment]
@markRichie 
Something like this
A
C
T
I
V
E
followed by other buttons in similar fashion.

**Comment by markRichie** [comment]
@vaarsha  ok 👍

**Comment by heyarviind** [comment]
How will this be useful? Can you please explain?

**Comment by markRichie** [comment]
fixed issue, check this #3  :)

**Comment by heyarviind** [comment]
@markRichie adding "break line" tag is not a good way, I've solved this with CSS #4

**Comment by ghosh** [comment]
@heyarviind "break line" is definitely bad. Your solution with `word-wrap` while works, it is dependent on the width. Changing the width will break your solution.

The correct way to approach this is using `text-orientation`, as done in #2.
